name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted
    
    steps:
    - name: pull Docker image
      run: sudo docker pull juanjodiazzz/easyjob-backend-cicd-pipeline:latest

    - name: Delete old Docker container
      run: sudo docker rm -f easyjob-backend-cicd-container || true

    - name: Run Docker container 
      env:
          PORT: 3000
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          DB_NAME: ${{secrets.DB_NAME}}
          DB_USER: ${{secrets.DB_USER}} 
          DB_PORT: ${{secrets.DB_PORT}}
          DB_HOST: ${{secrets.DB_HOST}}
          JWT_SECRET: ${{secrets.JWT_SECRET}}
          GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
          GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
          CALLBACK_URL: ${{secrets.GOOGLE_URL}}
          GOOGLE_PASSWORD: ${{secrets.GOOGLE_PASSWORD}}
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_S3_REGION: ${{secrets.AWS_S3_REGION}}
          S3_URL: ${{secrets.S3_URL}}
      run: |
        sudo docker run -d -p 3000:3000 --name easyjob-backend-cicd-container \
        -e PORT=$PORT \
        -e DB_PASSWORD=$DB_PASSWORD \
        -e DB_NAME=$DB_NAME \
        -e DB_USER=$DB_USER \
        -e DB_PORT=$DB_PORT \
        -e DB_HOST=$DB_HOST \
        -e JWT_SECRET=$JWT_SECRET \
        -e GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID \
        -e GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET \
        -e CALLBACK_URL=$CALLBACK_URL \
        -e GOOGLE_PASSWORD=$GOOGLE_PASSWORD \
        -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
        -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
        -e AWS_S3_REGION=$AWS_S3_REGION \
        -e S3_URL=$S3_URL \
        juanjodiazzz/easyjob-backend-cicd-pipeline:latest
