name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted
    
    steps:
    - name: pull Docker image
      run: sudo docker pull juanjodiazzz/easyjob-backend-cicd-pipeline:latest
    - name: Delete old Docker container
      run: sudo docker rm -f easyjob-backend-cicd-container || true
    - name: Run Docker container 
      env:
          PORT: 3000
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          DB_NAME: ${{secrets.DB_NAME}}
          DB_USER: ${{secrets.DB_USER}} 
          DB_PORT: ${{secrets.DB_PORT}}
          DB_HOST: ${{secrets.DB_HOST}}
          JWT_SECRET: ${{secrets.JWT_SECRET}}
          GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
          GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
          CALLBACK_URL: ${{secrets.GOOGLE_URL}}
          GOOGLE_PASSWORD: ${{secrets.GOOGLE_PASSWORD}}
      run: sudo docker run -d -p 3000:3000 --name easyjob-backend-cicd-container juanjodiazzz/easyjob-backend-cicd-pipeline
