name: Build and deploy Node.js app to Azure Web App - staynest

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install --force
          npm run build --if-present
          npm run test --if-present

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: bounceapp/render-action@0.6.0
        with:
          render-token: rnd_Y9vtVBTJaqzyY60StuDAbD3TsH8s
          serviceId: srv-cojv3863e1ms73bjogbg?key=U6oEpE9nzXQ
          retries: 20
          wait: 16000
          sleep: 30000
      
